
[theme]
name = "bad-wolf"
[theme.overrides]
idle_bg = "#06A284"
idle_fg = "#000000"
info_bg = "#003229"
info_fg = "#00EDBE"
good_bg = "#000000"
good_fg = "#00FFCC"
warning_bg = "#000000"
warning_fg = "#00FFCE"
critical_bg = "#D00426"
critical_fg = "#000000"
alternating_tint_bg = "#00FFCC"
separator = ''
[icons]
name = "awesome"
[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "net"
ssid = true
ip = true
device = "enp3s0"
speed_up = false
speed_down = false
[[block]]
block = "disk_space"
path = "/"
alias = "⛁"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%y"
[[block]]
block = "time"
interval = 1
format = "%I:%M:%S %P"

[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true
resolution = false
interval = 2
[[block]]
block = "uptime"
[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

