
[theme]
name = "solarized-dark"
[theme.overrides]
idle_bg = "#8F9B97"
idle_fg = "#1E2327"
info_bg = "#1D495B"
info_fg = "#8F9B97"
good_bg = "#133A49"
good_fg = "#CDBCA6"
warning_bg = "#254C5D"
warning_fg = "#8F9B97"
critical_bg = "#ab4642"
critical_fg = "#8F9B97"
[icons]
name = "awesome"
[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "net"
ssid = true
ip = true
device = "enp3s0"
speed_up = false
speed_down = false
[[block]]
block = "disk_space"
path = "/"
alias = "⛁"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%y %I:%M:%S %P"


[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true
resolution = false
interval = 2
[[block]]
block = "uptime"
[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

