
[theme]
name = "modern"
[theme.overrides]
idle_bg = "#333A47"
idle_fg = "#000000"
info_bg = "#2E3440"
info_fg = "#000000"
good_bg = "#5E81AC"
good_fg = "#000000"
warning_bg = "#2E3440"
warning_fg = "#81A1C1"
critical_bg = "#2E3440"
critical_fg = "#BF616A"
alternating_tint_bg = "#333A47"
separator = '🞀'
#    
[icons]
name = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "net"
device = "enp3s0"
ssid = false
ip = false
speed_down = true
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%y"
[[block]]
block = "time"
interval = 1
format = "%I:%M:%S %P"


[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true
resolution = false
interval = 2

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"

