
[theme]
<<<<<<< HEAD
name = "modern"
=======
name = "gruvbox-light"
>>>>>>> 6d22bce9693d8c226708521389530b81b7eab9d6
[theme.overrides]
idle_bg = "#333A47"
idle_fg = "#000000"
<<<<<<< HEAD
info_bg = "#2E3440"
info_fg = "#000000"
good_bg = "#5E81AC"
good_fg = "#000000"
warning_bg = "#2E3440"
warning_fg = "#81A1C1"
critical_bg = "#2E3440"
critical_fg = "#BF616A"
alternating_tint_bg = "#333A47"
separator = '🞀'
#    
=======
info_bg = "#003229"
info_fg = "#00EDBE"
good_bg = "#000000"
good_fg = "#3AFFD8"
warning_bg = "#2C78C4"
warning_fg = "#000000"
critical_bg = "#AE3C42"
critical_fg = "#000000"
alternating_tint_bg = "#00FFCC"

separator = ''
>>>>>>> 6d22bce9693d8c226708521389530b81b7eab9d6
[icons]
name = "awesome"

[[block]]
block = "uptime"

[[block]]
block = "focused_window"
max_width = 50

[[block]]
block = "net"
device = "enp3s0"
ssid = false
ip = false
speed_down = true
interval = 1

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "time"
interval = 1
format = "%a %d.%m.%y"
[[block]]
block = "time"
interval = 1
format = "%I:%M:%S %P"


[[block]]
block = "sound"

[[block]]
block = "xrandr"
icons = true
resolution = false
interval = 2

[[block]]
block = "battery"
interval = 10
format = "{percentage}%"
